"""empty message

Revision ID: 0f666e85bb49
Revises: be8e9a37744c
Create Date: 2023-06-15 01:47:45.042888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f666e85bb49'
down_revision = 'be8e9a37744c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('ingredients',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('elaboration',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('elaboration',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('ingredients',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
