"""empty message

Revision ID: 34db9ba8d7b3
Revises: 676be71b109d
Create Date: 2023-06-17 20:21:29.780649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34db9ba8d7b3'
down_revision = '676be71b109d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=5000),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=8000),
               existing_nullable=False)
        batch_op.alter_column('ingredients',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.String(length=10000),
               existing_nullable=True)
        batch_op.alter_column('elaboration',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.String(length=10000),
               existing_nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=3000),
               type_=sa.String(length=8000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=8000),
               type_=sa.VARCHAR(length=3000),
               existing_nullable=True)
        batch_op.alter_column('elaboration',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)
        batch_op.alter_column('ingredients',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=8000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###
