"""empty message

Revision ID: 484f771e166e
Revises: 0f666e85bb49
Create Date: 2023-06-16 14:07:02.175704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484f771e166e'
down_revision = '0f666e85bb49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recommended', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('is_recommended')

    # ### end Alembic commands ###
