"""empty message

Revision ID: d328699cbf06
Revises: 6f34dac75ac9
Create Date: 2023-05-27 01:09:29.841433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd328699cbf06'
down_revision = '6f34dac75ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_email_key', type_='unique')
        batch_op.drop_column('security_question')
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')
        batch_op.drop_column('security_answer')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('security_answer', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('security_question', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('favorite_email_key', ['email'])

    # ### end Alembic commands ###
