"""empty message

Revision ID: dafb6abd3dc9
Revises: 34db9ba8d7b3
Create Date: 2023-06-19 21:15:46.070689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafb6abd3dc9'
down_revision = '34db9ba8d7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_firebase', sa.String(length=8000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('image_firebase')

    # ### end Alembic commands ###
